window.SUPABASE_URL      = "https://csdnqwricljioxrcwmwj.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZG5xd3JpY2xqaW94cmN3bXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3NzUyNDYsImV4cCI6MjEwNjM1MTI0Nn0.Pw9gRAvbmxSLwKI3QrKKrr0S-p8Cg9n4AyUW3V_cjww";
